version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/usbdrive/sonarr/data:/config
      - /mnt/usbdrive/sonarr/tvseries:/tv #optional
      - /mnt/usbdrive/sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    
    radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/usbdrive/radarr/data:/config
      - /mnt/usbdrive/radarr/movies:/movies #optional
      - /mnt/usbdrive/radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    
    prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/usbdrive/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
